# Generated by Django 3.2.6 on 2023-07-01 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project_completedtasks_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='added',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='doned_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 7, 35, 28, 800532, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('doned', 'Doned'), ('inprocess', 'Inprocess'), ('free', 'Free')], default='free', max_length=50),
        ),
    ]
